const Data = [
    {
      id: 1,
      category: "education",
      icon: "icon-graduation",
      year: "Oct 2025 - Feb 2026",
      title: "Design of Memorable Experiences and Interfaces (UX/UI) Certificate",
      desc: "Learned to identify what customers perceive as value in order to apply tools that enable the design or redesign of products, services, and/or hybrid experiences that are memorable for customers.",
    },
    {
      id: 2,
      category: "education",
      icon: "icon-graduation",
      year: "2024 - 2025",
      title: "VFX Specialty - UP",
      desc: "Completed a specialization in Visual Effects at Universidad Panamericana, gaining experience in VFX pipelines, project workflows, and the creation and integration of digital elements into realistic environments. Developed skills in simulation, compositing, and technical problem-solving, including basic plugin scripting and tool development to optimize production processes.",
    },
    {
      id: 3,
      category: "education",
      icon: "icon-graduation",
      year: "2020 - 2025",
      title: "Digital Animation Engineering - UP",
      desc: "Earned a degree in Digital Animation Engineering from Universidad Panamericana, combining visual design, storytelling, and programming to build functional and user-centered digital products.",
    },
    {
      id: 4,
      category: "experience",
      icon: "icon-briefcase",
      year: "Feb 2026 - present",
      title: "UI/UX Designer – Anxo",
      desc: "Designed UI for mobile and web applications in Figma, ensuring usability and consistency. Developed a scalable design system and worked closely with developers to structure components and support implementation in code.",
    },
    {
      id: 5,
      category: "experience",
      icon: "icon-briefcase",
      year: "2022 - presente",
      title: "Web Design",
      desc: "Worked as an intern responsible for designing the Open Doors website within the Admissions Coordination team.",
    },
    {
      id: 6,
      category: "experience",
      icon: "icon-briefcase",
      year: "2022-presente",
      title: "Automation",
      desc: "Contributed as an intern to the automation of communication workflows for incoming students, improving efficiency and enhancing the overall user experience in collaboration with the Engineering Coordination team.",
    },
    {
      id: 7,
      category: "experience",
      icon: "icon-briefcase",
      year: "2018-presente",
      title: "Graphic Design",
      desc: "Developed visual content for digital platforms, including email signatures and social media posts for various clients, and led the overall visual identity of the Open Doors competition, maintaining brand consistency and enhancing visual communication.",
    },
  ];

export default Data
